openapi: 3.0.3
info:
  title: My API
  version: '1.0'
  description: Best API ever
  termsOfService: https://www.example.com
  contact:
    email: ashish@datacouch.io
    name: Ashish
    url: https://www.example.com/ashish
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://my-json-server.typicode.com/typicode/demo
    variables: {}
    description: Demo Server
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: My Dev server
paths:
  /users:
    summary: user level operations
    description: create and read users
    get:
      summary: fetch users
      description: reads user from server
      operationId: fetchUsers
      responses:
        2XX:
          description: successful fetch
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: abc123
                  username:
                    type: string
                    example: ashish
                  score:
                    type: integer
                    example: 55
                  active:
                    type: boolean
                    example: true
  /posts:
    summary: Posts operations
    description: create and view posts
    get:
      summary: fetch posts
      description: reads posts from the server
      operationId: fetchPosts
      responses:
        2XX:
          description: successful fetch
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
                  title:
                    type: string
                    example: Post 1
